# application-dev.yml
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never # separator: "$$"
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutos por defecto
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2