spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  cache:
    type: simple
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}